"""优化后的工具基类"""

from abc import ABC, abstractmethod
from typing import Any, Callable, Optional, get_type_hints
from pydantic import BaseModel
import inspect
import re


def tool_action(name: str = None, description: str = None):
    """装饰器：标记方法为可展开的工具action"""
    def decorator(func: Callable):
        func._is_tool_action = True
        func._tool_name = name
        func._tool_description = description
        return func
    return decorator


class ToolParameter(BaseModel):
    """工具参数定义"""
    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


class Tool(ABC):
    """工具基类，支持普通模式和可展开模式"""

    def __init__(self, name: str, description: str, expandable: bool = False):
        self.name = name
        self.description = description
        self.expandable = expandable

    @abstractmethod
    def run(self, parameters: dict[str, Any]) -> str:
        """执行工具"""
        pass

    @abstractmethod
    def get_parameters(self) -> list[ToolParameter]:
        """获取工具参数定义"""
        pass

    def get_expanded_tools(self) -> Optional[list['Tool']]:
        """获取展开后的子工具列表"""
        if not self.expandable:
            return None

        tools = [
            AutoGeneratedTool(self, method, method._tool_name, method._tool_description)
            for name, method in inspect.getmembers(self, predicate=inspect.ismethod)
            if hasattr(method, '_is_tool_action')
        ]
        return tools if tools else None

    def validate_parameters(self, parameters: dict[str, Any]) -> bool:
        """验证参数"""
        required_params = [p.name for p in self.get_parameters() if p.required]
        return all(param in parameters for param in required_params)

    def to_dict(self) -> dict[str, Any]:
        """转换为字典格式"""
        return {
            "name": self.name,
            "description": self.description,
            "parameters": [param.model_dump() for param in self.get_parameters()]
        }

    def to_openai_schema(self) -> dict[str, Any]:
        """转换为OpenAI function calling schema格式"""
        properties = {}
        required = []

        for param in self.get_parameters():
            prop = {"type": param.type, "description": param.description}
            
            if param.default is not None:
                prop["description"] = f"{param.description} (默认: {param.default})"
            
            if param.type == "array":
                prop["items"] = {"type": "string"}

            properties[param.name] = prop
            
            if param.required:
                required.append(param.name)

        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required
                }
            }
        }

    def __str__(self) -> str:
        return f"Tool(name={self.name})"

    def __repr__(self) -> str:
        return self.__str__()


class AutoGeneratedTool(Tool):
    """自动生成的工具 - 从方法签名和docstring自动提取参数"""

    # 类型映射
    TYPE_MAP = {
        str: "string", int: "integer", float: "number",
        bool: "boolean", list: "array", dict: "object"
    }

    def __init__(self, parent: Tool, method: Callable, name: str = None, description: str = None):
        self.parent = parent
        self.method = method

        # 生成工具名称
        if name is None:
            method_name = method.__name__.lstrip('_')
            name = f"{parent.name}_{method_name}"

        # 提取描述
        if description is None:
            description = self._extract_description()

        super().__init__(name=name, description=description)
        self._parameters = self._parse_parameters()

    def _extract_description(self) -> str:
        """从docstring提取描述"""
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"执行 {self.method.__name__}"

        for line in doc.split('\n'):
            line = line.strip()
            if line and not line.startswith(('Args:', 'Returns:')):
                return line

        return f"执行 {self.method.__name__}"

    def _parse_parameters(self) -> list[ToolParameter]:
        """从方法签名和docstring自动提取参数"""
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        param_descriptions = self._parse_param_descriptions()

        parameters = []
        for param_name, param in sig.parameters.items():
            if param_name == 'self':
                continue

            param_type_hint = type_hints.get(param_name, str)
            param_type = self._python_type_to_tool_type(param_type_hint)
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default
            description = param_descriptions.get(param_name, f"参数 {param_name}")

            parameters.append(ToolParameter(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))

        return parameters

    def _parse_param_descriptions(self) -> dict[str, str]:
        """从docstring解析参数描述"""
        docstring = inspect.getdoc(self.method) or ""
        descriptions = {}

        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)
        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        matches = re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL)

        for match in matches:
            param_name = match.group(1).strip()
            param_desc = re.sub(r'\s+', ' ', match.group(2).strip())
            descriptions[param_name] = param_desc

        return descriptions

    def _python_type_to_tool_type(self, py_type) -> str:
        """将Python类型转换为工具类型字符串"""
        origin = getattr(py_type, '__origin__', None)
        if origin is list:
            return "array"
        elif origin is dict:
            return "object"
        
        return self.TYPE_MAP.get(py_type, "string")

    def get_parameters(self) -> list[ToolParameter]:
        """获取参数列表"""
        return self._parameters

    def run(self, parameters: dict[str, Any]) -> str:
        """执行方法"""
        return self.method(**parameters)
